language: python
python:
  - "3.4"
  - "3.3"
services:
  - mongodb
  - postgresql
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo wget -O/etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list"
  - "wget -O- http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -"
  - "sudo apt-get update"
  - "yes | sudo apt-get upgrade"
  - "sudo apt-get install mongodb-org-server mongodb-org-shell"
  - "sudo apt-get install python2.7-dev python3-dev"
  - "sudo apt-get install libcouchbase2-core libcouchbase2-libevent libcouchbase-dev"
  - "wget http://dist.neo4j.org/neo4j-community-2.1.2-unix.tar.gz"
  - "tar xvfz neo4j-community-2.1.2-unix.tar.gz"
  - "neo4j-community-2.1.2/bin/neo4j start"
  - "sleep 5"
install: 
  - pip install -r requirements.txt
# # command to run tests, e.g. python setup.py test
script:
  - "export HPIT_ENV=travis"
  - python manager.py syncdb
  - python manager.py test
